# Generated by Django 5.0.6 on 2024-08-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='shipmet_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
