# Generated by Django 5.0.6 on 2024-08-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
    ]
